### ISSUE TITLE
External links in markdown cause exception

### ISSUE THREAD

**Issue by nlocascio** [actions4gh/configure-wiki#5]
When I attempt to add an external link to docs, it causes a failure:

```md
[This is an external link](https://www.google.com)
```

Failure:
```bash
node:internal/url:1463
    throw new ERR_INVALID_URL_SCHEME('file');
          ^

TypeError [ERR_INVALID_URL_SCHEME]: The URL must be of scheme file
    at fileURLToPath (node:internal/url:1463:[11](https://github.com/<project>/actions/runs/10390075851/job/28769685873#step:4:12))
    at file:///home/runner/work/_actions/actions4gh/configure-wiki/v1/dist/main.js:27849:35
    at overload (file:///home/runner/work/_actions/actions4gh/configure-wiki/v1/dist/main.js:25407:[12](https://github.com/<project>/actions/runs/10390075851/job/28769685873#step:4:13))
    at node (link) (file:///home/runner/work/_actions/actions4gh/configure-wiki/v1/dist/main.js:25354:27)
    at node (paragraph) (file:///home/runner/work/_actions/actions4gh/configure-wiki/v1/dist/main.js:25369:61)
    at node (root) (file:///home/runner/work/_actions/actions4gh/configure-wiki/v1/dist/main.js:25369:61)
    at visitParents (file:///home/runner/work/_actions/actions4gh/configure-wiki/v1/dist/main.js:25329:28)
    at visit (file:///home/runner/work/_actions/actions4gh/configure-wiki/v1/dist/main.js:25403:3)
    at file:///home/runner/work/_actions/actions4gh/configure-wiki/v1/dist/main.js:27847:3
    at wrapped (file:///home/runner/work/_actions/actions4gh/configure-wiki/v1/dist/main.js:26549:27) {
  code: 'ERR_INVALID_URL_SCHEME'
}
```

**Comment by ghost** [comment]
This also appears to be the case for anchor links, for example:

```md
[Information section](#information-section)
```

results in the same error being thrown.
